#!/usr/bin/env Rscript

lints <- lint_dir(here::here())
has_lints <- length(lints) > 0
lint_output <- NULL
if (has_lints) {
  lint_output <- paste(collapse = "\n", capture.output(print(lints)))
}
result <- testthat::expect(!has_lints,
                           paste(sep = "\n", "Not lint free", lint_output))
invisible(result)